{% set version = "12.0.0" %}
{% set sha256 = "be038bd8b83b82b79e2bbdd428b958f4662b1cc1747035af94f30c7fb1e76d08" %}

package:
  name: azure-storage-queues-cpp
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-storage-queues_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("azure-storage-queues-cpp", max_pin="x") }}

# https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-queues/vcpkg/vcpkg.json
requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - azure-core-cpp
    - azure-storage-common-cpp >=12.2.3

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - CMakeLists.txt
  commands:
    # shared libs
    - test -f ${PREFIX}/lib/libazure-storage-queues${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_BIN%\azure-storage-queues.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\azure-storage-queues.lib exit 1  # [win]

    # headers
    - test -f ${PREFIX}/include/azure/storage/queues.hpp          # [unix]
    - if not exist %LIBRARY_INC%\azure\storage\queues.hpp exit 1  # [win]

    # CMake metadata
    - test -f ${PREFIX}/share/azure-storage-queues-cpp/azure-storage-queues-cppTargets.cmake                     # [unix]
    - if not exist %LIBRARY_PREFIX%\share\azure-storage-queues-cpp\azure-storage-queues-cppTargets.cmake exit 1  # [win]

    # CMake find_package()
    - cmake $CMAKE_ARGS -G Ninja -S $RECIPE_DIR -B test-find-package    # [unix]
    - cmake %CMAKE_ARGS% -G Ninja -S %RECIPE_DIR% -B test-find-package  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Storage Queues Client Library for C++
  description: >-
    Azure Queue storage is a service for storing large numbers of messages that
    can be accessed from anywhere in the world via authenticated calls using
    HTTP or HTTPS. A single queue message can be up to 64 KB in size, and a
    queue can contain millions of messages, up to the total capacity limit of a
    storage account.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/storage/azure-storage-queues/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/storage/azure-storage-queues/

extra:
  recipe-maintainers:
    - teo-tsirpanis
    - jdblischak
    - jjerphan
    - Shelnutt2
